language: python
python: ["3.8"]
before_install: # See https://github.com/travis-ci/travis-ci/issues/8589
  - type -t deactivate && deactivate || true
  - export PATH=/opt/python/3.8/bin:$PATH
install:
  - make ce
script:
  - make test
  - make static-checks
